# Generated by Django 5.2.6 on 2025-09-16 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=150)),
                ('salaire', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('horaire_de_travail', models.IntegerField(blank=True, null=True)),
                ('lieu_de_poste', models.CharField(blank=True, max_length=255, null=True)),
                ('date_limite_postule', models.DateTimeField(blank=True, null=True)),
                ('document_necessaire', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Loisir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnnonceCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_obligatoire', models.BooleanField(default=False)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.annonce')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.competence')),
            ],
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('resume', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to='blog.candidat')),
            ],
        ),
        migrations.CreateModel(
            name='AnnonceCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.annonce')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.cv')),
            ],
        ),
        migrations.CreateModel(
            name='CVCompetence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(blank=True, max_length=50, null=True)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.competence')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='blog.cv')),
            ],
        ),
        migrations.CreateModel(
            name='CVFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('etablissement', models.CharField(blank=True, max_length=255, null=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to='blog.cv')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.formation')),
            ],
        ),
        migrations.CreateModel(
            name='AnnonceFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_obligatoire', models.BooleanField(default=False)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.annonce')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.formation')),
            ],
        ),
        migrations.CreateModel(
            name='CVLangue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(blank=True, max_length=50, null=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='langues', to='blog.cv')),
                ('langue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.langue')),
            ],
        ),
        migrations.CreateModel(
            name='AnnonceLangue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_obligatoire', models.BooleanField(default=False)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.annonce')),
                ('langue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.langue')),
            ],
        ),
        migrations.CreateModel(
            name='CVLoisir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loisirs', to='blog.cv')),
                ('loisir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.loisir')),
            ],
        ),
        migrations.CreateModel(
            name='AnnonceLoisir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_obligatoire', models.BooleanField(default=False)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.annonce')),
                ('loisir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.loisir')),
            ],
        ),
        migrations.AddField(
            model_name='annonce',
            name='poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='blog.poste'),
        ),
    ]
