# Generated by Django 5.2.6 on 2025-09-18 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatutEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salaire', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('candidat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.candidat')),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.poste')),
            ],
        ),
        migrations.CreateModel(
            name='Embauche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_changement', models.DateTimeField(auto_now_add=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.annonce')),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.candidat')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.employe')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueStatutEmploye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_changement', models.DateTimeField(auto_now_add=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.employe')),
                ('statut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.statutemploye')),
            ],
        ),
    ]
