# Generated by Django 5.2.6 on 2025-09-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos_cv/'),
        ),
    ]
