# Generated by Django 5.2.6 on 2025-09-19 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_statutemploye_employe_embauche_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correctreponse',
            options={},
        ),
        migrations.AlterModelOptions(
            name='planningentretient',
            options={},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.AlterModelOptions(
            name='questionreponse',
            options={},
        ),
        migrations.AlterModelOptions(
            name='reponse',
            options={},
        ),
        migrations.AlterModelOptions(
            name='scoreentretien',
            options={},
        ),
        migrations.AlterModelOptions(
            name='scorequestion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={},
        ),
        migrations.AlterModelOptions(
            name='testposte',
            options={},
        ),
        migrations.AlterModelOptions(
            name='testquestion',
            options={},
        ),
    ]
