# Generated by Django 5.2.6 on 2025-09-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cv_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatutCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
