# Generated by Django 5.2.6 on 2025-09-18 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_cv_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='email',
            field=models.EmailField(max_length=150),
        ),
    ]
