# Generated by Django 5.2.6 on 2025-09-18 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_authgroup_authgrouppermissions_authpermission_and_more'),
        ('blog', '0005_alter_candidat_email'),
    ]

    operations = [
    ]
